# Remote Embedded Diana Watcher
# For use w balena.io
# Merck, Summer 2018

# resin docker-compose is 2.1 max
version: '2.1'


services:

  proxy:
    image: derekmerck/orthanc-confd:latest-arm32v7
    ports:
      - "4242:4242"
    privileged: true
    environment:
      # Do not use Resin's init system on a non-Resin base
      INITSYSTEM: "on"
      ORTHANC_MAX_SIZE: 500
      ORTHANC_MAX_PATIENTS: 50
      ORTHANC_AET: DIANA
      ORTHANC_REMOTE_ENABLED: false
      # Include these in device environment vars
      # ORTHANC_PASSWORD: ${ORTHANC_PASSWORD}
      # ORTHANC_MOD_0: ${LOCAL_PACS_ADDR}
    # Use a tmpfs to avoid writing passwords to disk
    tmpfs:
      - /etc/orthanc

  diana:
    build: diana
    privileged: true
#    command: diana-cli watch -r index_studies pacs splunk
    environment:
      INITSYSTEM: "on"
      DIANA_SERVICES_PATH: /services.yml
      # Include these in device environment vars
      # ORTHANC_PASSWORD: ${ORTHANC_PASSWORD}
      # SPLUNK_HOST:      ${SPLUNK_HOST}
      # SPLUNK_HEC_TOKEN: ${SPLUNK_HEC_TOKEN}