---
proxy:

  host: 172.17.0.1
  port: 8999
  user: diana
  password: passw0rd!
  domains:
    pacs: DIANA

  query_domain: pacs
  query_level: DicomLevel.STUDIES
  query_dict:
    'ModalitiesInStudy': ""
    'StudyDescription': ""
  query_discovery_period: 300
  polling_interval: 120

  config_fp: /etc/orthanc/orthanc.json
  extra_modalities:
    - name: mock
      aet:  MOCK
      host: 192.168.1.115
      port: 2424

index:
  host: dev.central-imaging.com
  hec_port: 8088
  default_index: remotes
  default_token: remotes_tok
  hec_tokens:
    remotes_tok: "1b67778c-0b1d-4df9-8142-5c726e74b053"
